title: Jordan Dunfords Blog
author: Jordan Dunford
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Iâ€™m glad you are here. I plan to talk about my rise to the top of capitalism. Take a seat.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
